### ISSUE TITLE
Discussion and Post not working in my chatter application

### ISSUE THREAD

**Issue by MadMenan** [thedevdojo/chatter#86]
Hi i tried to install the chatter application in laravel 5.4, i got a error message when i create a new discussion and create the post. this is the error message. How can i fix it?

FatalThrowableError in ChatterBeforeNewDiscussion.php line 26:
Type error: Argument 2 passed to DevDojo\Chatter\Events\ChatterBeforeNewDiscussion::__construct() must be an instance of Illuminate\Support\Facades\Validator, instance of Illuminate\Validation\Validator given, called in /home/menan/www/fourm/vendor/devdojo/chatter/src/Controllers/ChatterDiscussionController.php on line 66

**Comment by CodeSkills** [comment]
Same here.

**Comment by fwartner** [comment]
Here too.

**Comment by fwartner** [comment]
https://github.com/thedevdojo/chatter/pull/80 is the fix!

Have added it manually to a fork.. In case you would like to use it:

composer.json:
```json
"require": {
        "devdojo/chatter": "dev-master",
    },

 "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/fwartner/chatter"
        }
    ],
```

**Comment by MadMenan** [comment]
@CodeSkills  I got another solution. i remove some code from ChatterDiscussionController store function

        // Event::fire(new ChatterBeforeNewDiscussion($request));
        // if (function_exists('chatter_before_new_discussion')) {
        //     chatter_before_new_discussion($request);
        // }

and ChatterPostController store function 
// Event::fire(new ChatterBeforeNewResponse($request, $validator));
        // if (function_exists('chatter_before_new_response')) {
        //     chatter_before_new_response($request, $validator);
        // }

**Comment by Chinese1904** [comment]
It was already fixed and pushed as well 👍

**Comment by lednhatkhanh** [comment]
Still happen on a new laravel install

**Comment by moseskamau338** [comment]
Still getting the issue again in a fresh install
On Laravel 6

**Comment by Tricabiz** [comment]
Giving bunch of errors in Laravel 6! Atleast tell us which version you support! WTH
